[tool.bandit]
exclude_dirs = ["venv"]

[tool.black]
line_length = 120
check = true

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true

[tool.coverage.run]
branch = true
source = ["."]
omit = ["manage.py", "social/*"]

[tool.flake8]
max_line_length = 120
extend_exclude = "venv"

[tool.isort]
profile = "black"
line_length = 120
check = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "social.settings"
